spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atguigudb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc123
mybatis:
  # 配置文件路徑
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper.xml路徑
  mapper-locations: classpath:mybatis/mapper/*-mapper.xml